### ISSUE TITLE
Add support for deleting layers

### ISSUE THREAD

**Issue by ryancbutler** [ryancbutler/UnideskSDK#13]
Create commands for deleting OS, Platform and App layers

**Comment by Siebrandf** [comment]
hey Ryan, I've put the following together which worked fine. the same should be done for OS and Platform layers. Can you verify the code and include it in the project if you're okay?

function remove-ALAppLayerRev
{
<#
.SYNOPSIS
  Removes a new layer version
.DESCRIPTION
  Removes a new layer version
.PARAMETER websession
  Existing Webrequest session for ELM Appliance
.PARAMETER appid
  Base application version layer id to use
.PARAMETER apprevid
  Application revision version layer id to use
.EXAMPLE
  $fileshare = Get-ALRemoteshare -websession $websession
  $appid = Get-ALapplayer -websession $websession|where{$_.name -eq "7-Zip"}
  $apprevid = get-alapplayerDetail -websession $websession -id $appid.Id
  $apprevid = $apprevid.Revisions.AppLayerRevisionDetail|where{$_.state -eq "Deployable"}|Sort-Object revision -Descending | select -First 1
  remove-alapplayerrev -websession $websession -appid $appid.Id -apprevid $apprevid.id -fileshareid $fileshare.id
#>  
[cmdletbinding(SupportsShouldProcess = $true, ConfirmImpact='High')]
Param(
[Parameter(Mandatory=$true)]$websession,
[Parameter(Mandatory=$true)]$appid,
[Parameter(Mandatory=$true)]$apprevid,
[Parameter(Mandatory=$true)]$fileshareid
)
Begin {
  Write-Verbose "BEGIN: $($MyInvocation.MyCommand)"
  Test-ALWebsession -WebSession $websession
}
Process {
[xml]$xml = @"
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
		<DeleteAppLayerRevisions xmlns="http://www.unidesk.com/">
		    <command>
				<LayerId>$appid</LayerId>
				<RevisionIds>
					<long>$apprevid</long>
				</RevisionIds>
				<Reason>
					<ReferenceNumber>0</ReferenceNumber>
				</Reason>
				<SelectedFileShare>$fileshareid</SelectedFileShare>
			</command>
		</DeleteAppLayerRevisions>
	</s:Body>
</s:Envelope>
"@
$headers = @{
SOAPAction = "http://www.unidesk.com/DeleteAppLayerRevisions";
"Content-Type" = "text/xml; charset=utf-8";
UNIDESK_TOKEN = $websession.token;
}
$url = "https://" + $websession.aplip + "/Unidesk.Web/API.asmx"
if ($PSCmdlet.ShouldProcess("Removing $apprevid from $appid")) {
  $return = Invoke-WebRequest -Uri $url -Method Post -Body $xml -Headers $headers -WebSession $websession
  [xml]$obj = $return.Content

  if($obj.Envelope.Body.DeleteAppLayerRevisionsResponse.DeleteAppLayerRevisionsResult.Error)
  {
    throw $obj.Envelope.Body.DeleteAppLayerRevisionsResponse.DeleteAppLayerRevisionsResult.Error.message

  }
  else {
    Write-Verbose "WORKTICKET: $($obj.Envelope.Body.DeleteAppLayerRevisionsResponse.DeleteAppLayerRevisionsResult.WorkTicketId)"
    return $obj.Envelope.Body.DeleteAppLayerRevisionsResponse.DeleteAppLayerRevisionsResult
  }
}

}
end{Write-Verbose "END: $($MyInvocation.MyCommand)"}
}

**Comment by ryancbutler** [comment]
Added with #18
