### ISSUE TITLE
get-alvmname when task is in error state

### ISSUE THREAD

**Issue by bnickerson-fnba** [ryancbutler/UnideskSDK#15]
When a task is in an error state, such as a failed finalize, the status is different than a normal task.  The Regex doesn't match the pattern, it's in quotations instead of between brackets.

**Comment by ryancbutler** [comment]
Thanks!  Would you be able to share an example message?

**Comment by bnickerson-fnba** [comment]
Here you go: 

> An error occurred while finalizing version 'Test' of Layer '1709-DEV-Gradle'. Please address this issue and retry: The virtual machine
> '1709-DEV-Gradle-2019-01-09_08-45-35.717 (Citrix App Layering Packaging Machine)' could not be imported. The virtual machine could not be found.

**Comment by ryancbutler** [comment]
They don't make that very friendly, do they?  I'll play around with some options when I get a chance.

**Comment by bnickerson-fnba** [comment]
I have a newbie level of knowledge when it comes to RegEx, but I came up with this and it seems to work.

(?<=(\]|'))([^'\[]*)\(Citrix([^)]+)\)([^\[']*)(?=(\[|'))

**Comment by ryancbutler** [comment]
Awesome!  Would you want to give a pull request a whirl or want me to add?

**Comment by bnickerson-fnba** [comment]
I can give it a try. I'll have to figure out how to do it.
