### ISSUE TITLE
Add feature to clone applayer

### ISSUE THREAD

**Issue by josephhu-personal** [ryancbutler/UnideskSDK#35]
![image](https://user-images.githubusercontent.com/46542760/71539616-e1a11c80-290c-11ea-80b7-d0321b68d045.png)

**Comment by Siebrandf** [comment]
Can I take the freedom to work on this?

**Comment by ryancbutler** [comment]
@Siebrandf of course!  I was thinking this might already be possible with the current commands with the *get-* and *new-* but if you want to create a new function I'm all for it!

**Comment by ryancbutler** [comment]
This has been added
