### ISSUE TITLE
New AppLayer version support prerequisite layers

### ISSUE THREAD

**Issue by sommerers** [ryancbutler/UnideskSDK#39]
Wanting to see if you can add something to the new-alapplayerrev to include prerequisite layers. I assume something similar to how you added if platform layer was selected then include this snipped of code.

**Comment by paulmainstone-emg** [comment]
Hi, yes, Id like to also see this. Currently use this to automate 99% of the layer creation. Just need to be able to add a dependent layer into a new layer creation. Thanks

**Comment by ryancbutler** [comment]
Will try to look into this when I can.

**Comment by ryancbutler** [comment]
Shoot missed the actual new app layer.  Have it added for the new rev.

**Comment by ryancbutler** [comment]
This is now added to [0.3.16](https://www.powershellgallery.com/packages/ctxal-sdk/0.3.16).  And usage can be found https://github.com/ryancbutler/UnideskSDK#new-application-prerequisite-layer and https://github.com/ryancbutler/UnideskSDK#new-application-prerequisite-layer-version

**Comment by paulmainstone-emg** [comment]
Thanks Ryan - much appreciated
