### ISSUE TITLE
New-alapplayerrev -version Variable

### ISSUE THREAD

**Issue by sommerers** [ryancbutler/UnideskSDK#4]
This may be more of a question or clarification than an issue. In new-alapplayerrev the -version <Object> in your example is "9.0" I wanted to find out if this represents the $apprevid.DisplayedVersion or is this an Increment of the $apprevid.DisplayedVersion? So if the Display Version is 8.0 I should increment it to whatever version this is and then use this new value as the -version?

**Comment by ryancbutler** [comment]
Hopefully I'm following your question right.  The `-version` would be the NEW version while the `-apprevid` would be the ID of the layer to upgrade from.

**Comment by ryancbutler** [comment]
closing for now
