### ISSUE TITLE
Change to Add-ALelappassignment

### ISSUE THREAD

**Issue by paulmainstone-emg** [ryancbutler/UnideskSDK#44]
Hi Ryan

Slight change to **Add-ALelappassignment.ps1**. Couple of things

1. You don't need to specify and image to assign a user\group to the elastic app layer. In fact you wouldn't an to if you only want to use it as an elastic layer to any image based on user group. I believe adding it the image means that it will also ways be available to all users

The Add-ALelappassignment.ps1 specifies $imageid as a mandatory variable; however it doesnt need to be. I have changed my version to mandatory = false which allows me to set the assignment to a user group and not an image.

2. I had to pass all the group details to the command rather than sending the object as it wouldn't process them without this. For example I had to use this;

_$FindGroup = Get-ALLdapobject -websession $ALWebsession -object $ElasticUserGroups

Add-ALElAppAssignment -websession $ALWebSession -apprevid $ApplicationVersionRevID.Id -unideskid $FindGroup.UnideskId -objecttype $FindGroup.ObjectType-directoryjunctionid $FindGroup.directoryjunctionid -ldapguid $FindGroup.guid -ldapdn $FindGroup.dn -sid $FindGroup.sid -Confirm:$False_

rather than this

_$user = get-alldapobject -websession $websession -object "myusername"

add-alelappassignment -websession $websession -apprevid $apprevid.Id -user $user_

So I then had to update the **Add-ALelappassignment.ps1** to accept that

See below for my version - I may have just been doing something wrong doing it your way.

function Add-ALELAppassignment {
  <#
.SYNOPSIS
  Adds a user account or group to an applications elastic layer assignment
.DESCRIPTION
  Adds a user account or group to an applications elastic layer assignment
.PARAMETER websession
  Existing Webrequest session for ELM Appliance
.PARAMETER apprevid
  Application version layer ID
.PARAMETER user
  LDAP located user object
.EXAMPLE
  $user = get-alldapobject -websession $websession -object "myusername"
  add-alelappassignment -websession $websession -apprevid $apprevid.Id -user $user
.EXAMPLE
  $users = @('MyGroup1','MyGroup2','Domain Users')
  $finduser = $users|get-alldapobject -websession $websession
  $app = Get-ALapplayerDetail -websession $websession|where{$_.name -eq "Libre Office"}
  $apprevs = Get-ALapplayerDetail -websession $websession -id $app.Id
  $apprevid = $apprevs.Revisions.AppLayerRevisionDetail|where{$_.state -eq "Deployable"}|Sort-Object revision -Descending|select -First 1
  $add = $finduser|add-alelappassignment -websession $websession -apprevid $apprevid.Id
#>
  [cmdletbinding(SupportsShouldProcess = $true, ConfirmImpact = 'High')]
  Param(
    [Parameter(Mandatory = $true)]$websession,
    [Parameter(Mandatory = $true)][string]$apprevid,
    [Parameter(Mandatory = $true)][long]$unideskid,
       [Parameter(Mandatory = $true)][long]$directoryjunctionid,
       [Parameter(Mandatory = $true)][string]$ldapguid,
       [Parameter(Mandatory = $true)][string]$ldapdn,
       [Parameter(Mandatory = $true)][string]$sid,
       [Parameter(Mandatory = $true)][string]$objecttype,
       [Parameter(Mandatory = $false)][long]$imageid
  )
  Begin {
    Write-Verbose "BEGIN: $($MyInvocation.MyCommand)"
    Test-ALWebsession -WebSession $websession
  }
  Process {
    [xml]$xml = @"
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <UpdateAppLayerAssignment xmlns="http://www.unidesk.com/">
      <command>
        <AdEntityIds>
          <DirectoryId xsi:type="$objecttype">
            <UnideskId>$unideskid</UnideskId>
            <DirectoryJunctionId>$directoryjunctionid</DirectoryJunctionId>
            <LdapGuid>$ldapguid</LdapGuid>
            <LdapDN>$ldapdn</LdapDN>
            <Sid>$sid</Sid>
          </DirectoryId>
        </AdEntityIds>
        <LayeredImageIds>
          <long>$imageid</long>
        </LayeredImageIds>
        <AppLayerRevId>$apprevid</AppLayerRevId>
        <Reason>
          <ReferenceNumber>0</ReferenceNumber>
        </Reason>
      </command>
    </UpdateAppLayerAssignment>
  </s:Body>
</s:Envelope>
"@
    Write-Verbose $xml
    $headers = @{
      SOAPAction     = "http://www.unidesk.com/UpdateAppLayerAssignment";
      "Content-Type" = "text/xml; charset=utf-8";
      UNIDESK_TOKEN  = $websession.token;
    }
    if ($PSCmdlet.ShouldProcess("Adding $apprevid to $($user.DN)")) {
      $url = "https://" + $websession.aplip + "/Unidesk.Web/API.asmx"
      $return = Invoke-WebRequest -Uri $url -Method Post -Body $xml -Headers $headers -WebSession $websession
      [xml]$obj = $return.Content
    }
  }

  end {
    if ($PSCmdlet.ShouldProcess("Output for application add")) {
      if ($obj.Envelope.Body.UpdateAppLayerAssignmentResponse.UpdateAppLayerAssignmentResult.Error) {
        throw $obj.Envelope.Body.UpdateAppLayerAssignmentResponse.UpdateAppLayerAssignmentResult.Error.message

      }
      else {
        Write-Verbose "WORKTICKET: $($obj.Envelope.Body.UpdateAppLayerAssignmentResponse.UpdateAppLayerAssignmentResult.WorkTicketId)"
        return $obj.Envelope.Body.UpdateAppLayerAssignmentResponse.UpdateAppLayerAssignmentResult.WorkTicketId
      }
    }
    Write-Verbose "END: $($MyInvocation.MyCommand)"
  }

} 

I hope this makes sense

Thanks Paul

**Comment by ryancbutler** [comment]
Thanks @paulmainstone-emg.  Do you want to try a pull request?
