### ISSUE TITLE
PSCredential Sanitization

### ISSUE THREAD

**Issue by chisho21** [ryancbutler/UnideskSDK#48]
Per the note in README: 

> Note: If your password contains a &,<,>,",' you will need to convert with [System.Security.SecurityElement]::Escape(MY&PASSWORD) to handle the special character(s) Thanks for the hint Travis Adams!

Passing an "un-sanitized" credential will produce an error with users credential in clear text on the screen and powershell logging if enabled.

**Comment by ryancbutler** [comment]
Closed with #50
