### ISSUE TITLE
XML is formatted incorrectly in Add-ALELAppassignment

### ISSUE THREAD

**Issue by expired00** [ryancbutler/UnideskSDK#56]
Line 55  `<Sid>$sid<Sid/>`
Line 59  `<long>$imageid<long/>`

Slashes are on the wrong side

**Comment by expired00** [comment]
Here's the corrected block
`        [xml]$xml = @"
  <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <UpdateAppLayerAssignment xmlns="http://www.unidesk.com/">
        <command>
          <AdEntityIds>
            <DirectoryId xsi:type="$objecttype">
              <UnideskId>$unideskid</UnideskId>
              <DirectoryJunctionId>$directoryjunctionid</DirectoryJunctionId>
              <LdapGuid>$ldapguid</LdapGuid>
              <LdapDN>$ldapdn</LdapDN>
              <Sid>$sid</Sid>
            </DirectoryId>
          </AdEntityIds>
          <LayeredImageIds>
            <long>$imageid</long>
          </LayeredImageIds>
          <AppLayerRevId>$apprevid</AppLayerRevId>
          <Reason>
            <ReferenceNumber>0</ReferenceNumber>
          </Reason>
        </command>
      </UpdateAppLayerAssignment>
    </s:Body>
  </s:Envelope>
"@`

**Comment by ryancbutler** [comment]
Thank you! Fix in 0.3.25
