### ISSUE TITLE
New-ALPlatformLayer - Provisioning & Broker type not detected

### ISSUE THREAD

**Issue by sommerers** [ryancbutler/UnideskSDK#60]
I've noticed when creating a new Platform Layer with the New-ALPlatformLayer that even when the ProvisioningPlatformTypeID and BrokerPlatformTypeID are set it's displaying as None' None' in the Task/Finalized Layer Audit History.

The options I'm choosing are pvs and xendesktop.

When I use the Get-ALPlatformDetail to look up the ID I don't see anything in the innerxml for either the provisioningplatformTypeID or BrokerPlatformTypeID

Was curious if something change or if it's something on my end.

ELM 22.4.0.1003
SDK 0.3.27

**Comment by ryancbutler** [comment]
@Khazaa any thoughts here?

**Comment by Khazaa** [comment]
Hello,

I found the Problem.
In New-ALPlatformlayer.ps1, the parameters ProvisioningPlatformTypeID and BrokerPlatformTypeID will only set to the Layer, if the Type-Parameter is set to "Publish". With "Create" only HypervisorPlatformTypeId will be used.

@sommerers Is the layer not working without these settings? I use this for month and have no problems with it.

Edit:
I thought about it. When we create a platformlayer, we build a "base-layer" with no changes in it. Then we build another layer-revision, with all the changes we need in there. When we do/need updates, we build a new layer-revision with the base-layer, so the new revision is always clean.
So we don't need the parameters. If you work with the "base-layer", u need the parameters.

But I don't know, if you could easily use "-type Publish".. just test it :)

**Comment by sommerers** [comment]
Thanks for the quick response. Once set to -type Publish it worked for me.
